### ISSUE TITLE
Static IP feedback with k8s via AWS EKS

### ISSUE THREAD

**Issue by mlissner** [juggernaut/webhook-sentry#14]
I spent the past few weeks working off and on to get a static IP added to an existing EKS cluster. I'm not sure if I'm bad at this (probably), or if it's just hard for everybody, but it took a lot of trial and error. I put a bunch of notes over here: https://github.com/freelawproject/courtlistener/issues/2273#issuecomment-1386258025

Is there value in adding some or all of these notes to this repo somewhere? I'd be happy to do an addition to the readme or a Wiki page if you want to turn that feature on in the Github settings. (Or maybe this issue is enough!)

Anyway, our system utilizing webhook-sentry is deploying now and we're really excited to get static egress and the security benefits this offers. Thank you once more!

**Comment by juggernaut** [comment]
Apologies for the delayed response here @mlissner  -- it would absolutely be useful to have that info in the readme. Please send a PR to add it to the README when you get the chance.
